wcs_coav_user:
    resource: "@WCSCoavBundle/Controller/UserController.php"
    type:     annotation

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Controller/ReservationController.php"
    type:     annotation

wcs_coav_flight:
    resource: "@WCSCoavBundle/Controller/FlightController.php"
    type:     annotation

wcs_coav_user:
    resource: "@WCSCoavBundle/Controller/UserController.php"
    type:     annotation

wcs_coav_plane_model:
    resource: "@WCSCoavBundle/Controller/PlaneModelController.php"
    type:     annotation

wcs_coav_terrain:
    resource: "@WCSCoavBundle/Controller/TerrainController.php"
    type:     annotation

wcs_coav_flight:
    resource: "@WCSCoavBundle/Controller/FlightController.php"
    type:     annotation

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Controller/ReservationController.php"
    type:     annotation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /

wcs_coav_listingcontroller:
    resource: "@WCSCoavBundle/Controller/ListingControllerController.php"
    type:     annotation

wcs_coav_reviewcontroller:
    resource: "@WCSCoavBundle/Controller/reviewController.php"
    type:     annotation


