# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            fos_userbundle:
                id: fos_user.user_provider.username

        firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager

                logout:       true
                anonymous:    true

        access_control:
            - #form_login: ~	+ - { path: ^/$, role: IS_AUTHENTICATED }
            - { path: ^/planemodel, role: IS_AUTHENTICATED }
            - { path: ^/flight, role: IS_AUTHENTICATED }
            - { path: ^/reservation, role: IS_AUTHENTICATED }
            - { path: ^/terrain, role: IS_AUTHENTICATED }
            - { path: ^/review, role: IS_AUTHENTICATED }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
